### PR TITLE
Add Optimzing Search

### LINKED ISSUE #39: Optimzing Search on Foreign Keys
The problem associated with a search on foreign keys is related to the N+1 problem where more than required times the Database is hit, which we can reduce by using `select_related` and `prefetch_related` for one to many and many to many keys where joins would allow DB to be hit only once rather than multiple times reducing the querying time.

InstiApp/lite-hai-backend#80 and InstiApp/lite-hai-backend#82 can be taken as a reference for this

### PR DESCRIPTION
**Pull request by JeeveshGarg**
Fixes #39

### CODE REVIEW

**Comment by king-11** [comment]
How is it different from the last one just wanted to know before reviewing... Also you should have made commits to the last PR only shouldn't have created multiple PRs for same thing.

**Comment by JeeveshGarg** [comment]
now i get to know difference between select_related and prefetch_related and your statement "Its for use cases when we will, later on, try to access a field"

About new PR, in earlier PR i got issues in env setup, their is correction in setup instruction in readme file ig, that why i setup project from scratch again.

**Comment by king-11** [comment]
Cool I will try to give you a review by tomorrow or day after tomorrow thanks for taking up the issue 😄

**Comment by king-11** [comment]
Hey @JeeveshGarg I think we can hasten up the process of reviewing if you can explain me your changes in a meet... So can you join the VC at 3PM Today?

**Comment by JeeveshGarg** [comment]
Okay.

**Comment by JeeveshGarg** [comment]
@king-11 PTAL, will make separate PR for issue #38 (with migration).

**Comment by king-11** [comment]
@JeeveshGarg you still have to push in the migrations lemme know when you are done with that

**Review by king-11 — APPROVED** [review]
LGTM 👍🏻  good job

**Pull request merged**
